### ISSUE TITLE
Compile error when using Ivy and Angular 9

### ISSUE THREAD

**Issue by zackarychapple** [angular-material-extensions/password-strength#240]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

MacOS Mojave
### Versions

```Angular CLI: 9.0.0-rc.0
Node: 12.10.0
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/fire                     5.2.1
@angular/flex-layout              6.0.0-beta.16
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               8.3.3
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

### Repro steps

1. Install via the `ng add @angular-material-extensions/password-strength` command.
1. Post install ivy compile fails with the below error. 

### The log given by the failure

```
Compiling @angular-material-extensions/password-strength : es2015 as esm2015
Error: Error on worker #1: Error: Tried to overwrite /Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@ngrx/effects/src/actions.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:36:23)
    at NewEntryPointFileWriter.writeFile (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:63:53)
    at /Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:45:69
    at Array.forEach (<anonymous>)
    at NewEntryPointFileWriter.writeBundle (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:45:30)
    at ClusterWorker.compile (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/main.js:166:32)
    at Worker.<anonymous> (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:41:42)
    at Worker.emit (events.js:209:13)
    at process.<anonymous> (internal/cluster/worker.js:30:12)
    at process.emit (events.js:209:13)
    at ClusterMaster.onWorkerMessage (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/tslib/tslib.js:117:57)
    at /Users/zackaryc/code/newNgAtlanta/conferences/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/Users/zackaryc/code/newNgAtlanta/conferences/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:209:13)
```

**Comment by AnthonyNahas** [comment]
I am sorry, but angular v9 is not supporet at the moment! 

Thanks for understanding

**Comment by zackarychapple** [comment]
@AnthonyNahas thank you for the feedback :) I'm one of the GDE's testing Angular v9. I opened this issue because it is causing issues for Ivy when using 9. Its more of a heads up that its going to be an issue.  Given that 9 is in rc.1 now I thought it might be helpful to know.

**Comment by AnthonyNahas** [comment]
@zackarychapple I have really the honor to have you here as a collaborator ❤️ 

I will add that to the todo list! 


Since the library is recording more than 3k downloads per week, it would be helpful to support angular 9 during the rc phase 


thank you once again! 🍻

**Comment by andbjer** [comment]
Angular v9 is now officially released. Any plans on adding support for Angular v9 in the near future?

**Comment by AnthonyNahas** [comment]
yes, I think either tonight or tomorrow I will publish a major release

**Comment by AnthonyNahas** [comment]
this is already fixed yesterday! congrats! [v6](https://www.npmjs.com/package/@angular-material-extensions/password-strength) is out!

**Comment by turnono** [comment]
this error is still happening on version 6 and 7, I am on Angular 10

node_modules/ngx-auth-firebaseui/node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js:668:26 - error NG1010: Value at position 1 in the NgModule.imports of MatPasswordStrengthModule is not a reference: [object Object]
[ng] 668                 imports: [
[ng]                              ~
[ng] 669                     CommonModule,
[ng]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] ... 
[ng] 673                     MatRippleModule
[ng]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 674                 ],
[ng]     ~~~~~~~~~~~~~~~~~
